server:
  port: 8020
spring:
  application:
    name: movieprovider
user:
  userServiceUrl: http://localhost:8000/

info:
  app:
    name: @project.artifactId@
    java:
      source: @java.version@
      target: @java.version@