server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters[0]: DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials,RETAIN_FIRST
      routes:
        - id: shop-user
          uri: http://localhost:8003/
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: shop-supplier
          uri: http://localhost:8020/
          predicates:
            - Path=/supplier/**
          filters:
            - StripPrefix=1
        - id: shop-order
          uri: http://localhost:8001/
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: shop-product
          uri: http://localhost:8002/
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/