server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: shop-user
          uri: http://localhost:8003/
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/